### ISSUE TITLE
Error with matplotlib

### ISSUE THREAD

**Issue by 2007lab** [hagax8/ancestry_viz#1]
`python runGTM.py --model GTM --data data/recoded_1000G.mat --labels data/recoded_1000G.raw.noadmixed.lbls3 --labeltype discrete --out data/1000G_GTMbuildV01 --pca --n_components 10 --regularization 0.1 --rbf_width_factor 0.3 --missing --missing_strategy median --random_state 8 --ids vj.1000g.ids

Namespace(alpha=0.5, cname='Spectral_r', crossvalidate=False, filenamedat='data/recoded_1000G.mat', filenameids='vj.1000g.ids', filenamelbls='data/recoded_1000G.raw.noadmixed.lbls3', filenametestids=None, grid_size=0, interpolate=False, kernel='euclidean', labeltype='discrete', missing=True, missing_strategy='median', model='GTM', n_components=10, n_neighbors=1, output='data/1000G_GTMbuildV01', pca=True, pointsize=1.0, predict_mode='bayes', prior='equiprobable', random_state=8, rbf_grid_size=0, rbf_width_factor=0.3, regularization=0.1, representation='modes', svm_epsilon=1.0, svm_gamma=1.0, svm_margin=1.0, test=None, usetest=None, verbose=False)

User provided model, data file and label names.

Used 10 components explaining 7.46560685665743% of the variance

k:17, m:4, regul:0.1, s:0.3
time taken for GTM:  22.735700845718384
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/colors.py", line 174, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: (6, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4232, in scatter
    colors = mcolors.to_rgba_array(c)
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/colors.py", line 275, in to_rgba_array
    result[i] = to_rgba(cc, alpha)
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/colors.py", line 176, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/colors.py", line 227, in _to_rgba_no_colorcycle
    raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
ValueError: Invalid RGBA argument: 6

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runGTM.py", line 509, in <module>
    prior=args.prior, do_interpolate=args.interpolate)
  File "/home/user/anaconda3/lib/python3.7/site-packages/ugtm/ugtm_classes.py", line 459, in plot_multipanel
    prior=prior)
  File "/home/user/anaconda3/lib/python3.7/site-packages/ugtm/ugtm_plot.py", line 153, in plotMultiPanelGTM
    edgecolor="black")
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4245, in scatter
    .format(nc=n_elem, xs=x.size, ys=y.size)
ValueError: 'c' argument has 1976 elements, which is not acceptable for use with 'x' with size 2504, 'y' with size 2504.
`

**Comment by 2007lab** [comment]
Still awaiting a resolution.
